### PR TITLE
feat(toggle component): added toggle component to pebbles library

### PR DESCRIPTION
**Pull request by luizdanielmlima**
## Description

Added toggle component

## Motivation and Context

The toggle component was added as one of the "Form controls" options needed in the library.

## How Has This Been Tested?

No tests

## Types of changes

- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Build (Changes that affect the build system or dependencies)
- [ ] Chore (Other changes that do not modify src or test files)
- [ ] CI (Changes to our CI configration and scripts)
- [ ] Docs (Changes to documentation files)
- [ ] Style (Changes to coding style, like linters and prettier)
- [ ] Refactor (Changes that do not add new functionality or alter current ones)
- [ ] Performance (Performance improvements)
- [ ] Test (Adding or changing tests or the testing setup)
- [ ] Revert (Reverting a previous change)

## Checklist:

- [x] I have made sure my changes work properly on iOS devices running Safari.
- [x] I have made sure my changes work properly on Android devices running Chrome.
- [x] I have made sure my changes work properly on Desktop.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://18--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://18--logrock-pebbles.netlify.app&speed=1

**Review by lipe-dev — COMMENTED** [review]
Make sure the component shows/works properly on mobile devices using the generated browserstack link, the password should be on your onePassword, let me know if it is not.

Once you do that, check the respective checkmarks on your PR description above and we can merge it :D

Great job! component looks neat.

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://18--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://18--logrock-pebbles.netlify.app&speed=1

**Pull request merged**
