### PR TITLE
feat(select): :sparkles: add select component

### PR DESCRIPTION
**Pull request by lipe-dev**
## Description

Adds a Select component, that should work like the default select from HTML, but look cooler.

## Motivation and Context

This is a required input for our new onboarding process. This was ported from granite's autocompleteinput, and changed to match our design system.

## How Has This Been Tested?

visual testing on storybook

## Screenshots (if appropriate):

See storybook preview below.
Note that on mobile the dropdown list does not show until the component has focus, in which case it becomes a full screen input, with the text input on top and the dropdown list below it.

- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Build (Changes that affect the build system or dependencies)
- [ ] Chore (Other changes that do not modify src or test files)
- [ ] CI (Changes to our CI configration and scripts)
- [ ] Docs (Changes to documentation files)
- [ ] Style (Changes to coding style, like linters and prettier)
- [ ] Refactor (Changes that do not add new functionality or alter current ones)
- [ ] Performance (Performance improvements)
- [ ] Test (Adding or changing tests or the testing setup)
- [ ] Revert (Reverting a previous change)

### CODE REVIEW

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://7--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://7--logrock-pebbles.netlify.app&speed=1

**Review by george-silva — APPROVED** [review]
After careful review this LGTM

**Comment by lipe-dev** [comment]
> After careful review this LGTM
@george-silva 
image

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://7--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://7--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://7--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://7--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://7--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://7--logrock-pebbles.netlify.app&speed=1

**Pull request merged**
