### PR TITLE
Stepper upgrade (Breaking changes!)

### PR DESCRIPTION
**Pull request by luizdanielmlima**
## Description

This is an upgrade to the Stepper component, to allow different/flexible content inside each step. BUT, this brings breaking changes to the previous Stepper, so a refactor should be made to existing components.

## Motivation and Context

Allow more freedom when using the Stepper on a variety of UIs.

### Desktop
image

## Types of changes

- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Build (Changes that affect the build system or dependencies)
- [ ] Chore (Other changes that do not modify src or test files)
- [ ] CI (Changes to our CI configration and scripts)
- [ ] Docs (Changes to documentation files)
- [ ] Style (Changes to coding style, like linters and prettier)
- [ ] Refactor (Changes that do not add new functionality or alter current ones)
- [ ] Performance (Performance improvements)
- [ ] Test (Adding or changing tests or the testing setup)
- [ ] Revert (Reverting a previous change)

## Checklist:

- [ ] I have made sure my changes work properly on iOS devices running Safari.
- [ ] I have made sure my changes work properly on Android devices running Chrome.
- [x] I have made sure my changes work properly on Desktop.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://97--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://97--logrock-pebbles.netlify.app&speed=1

**Review by lipe-dev — APPROVED** [review]
this looks great @luizdanielmlima . good job.
can you add a snapshot test? you can render and snapshot what you`ve added to the stories (one example of each), just so we get some cov.

**Comment by lipe-dev** [comment]
One more thing, did you remember to add the BREAKING CHANGE footer to any of your commits?
If not, please add it (you can amend an existing one).

It`s just a simple text line in the commit message, like this:

```
fix(something): do whatever

BREAKING CHANGE: this breaks the stepper API, requiring client changes
```

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://97--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://97--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://97--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://97--logrock-pebbles.netlify.app&speed=1

**Pull request merged**
