### PR TITLE
New date picker

### PR DESCRIPTION
**Pull request by lipe-dev**
- Add peer dependency to mui-x/date-picker
- Create a custom input implementation for the date-picker's `field` slot, which renders our default input in its place
- Adapt all props from-to-from our base input
- Style according to the new design
- Upgrade some dependencies to fix a bunch of issues
- Fix a lot of 💩 typings

### CODE REVIEW

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://173--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://173--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://173--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://173--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://173--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://173--logrock-pebbles.netlify.app&speed=1

**Review by rodrigosakamoto — APPROVED** [review]

**Review by giuliapignati — APPROVED** [review]

**Review by G-PPeralta — APPROVED** [review]

**Pull request merged**
