### PR TITLE
Datepicker improvements

### PR DESCRIPTION
**Pull request by luizdanielmlima**
## Description

Datepicker component bug fixes and UX improvements:

1) Implements MM/DD/YYYY Mask
2) Add a "chevron" (up/down) on the year picker (right now is just a grey are, which makes it difficult for the user to understand he/she can scroll up/down through the years)
3) Fix a bug in the uppermost year (the hover "jumps" to the "up scroll area", making it erratic to choose the year)

### Desktop
image

## Types of changes

- [ x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Build (Changes that affect the build system or dependencies)
- [ ] Chore (Other changes that do not modify src or test files)
- [ ] CI (Changes to our CI configration and scripts)
- [ ] Docs (Changes to documentation files)
- [ ] Style (Changes to coding style, like linters and prettier)
- [ ] Refactor (Changes that do not add new functionality or alter current ones)
- [ ] Performance (Performance improvements)
- [ ] Test (Adding or changing tests or the testing setup)
- [ ] Revert (Reverting a previous change)

## Checklist:

- [ ] I have made sure my changes work properly on iOS devices running Safari.
- [ ] I have made sure my changes work properly on Android devices running Chrome.
- [x ] I have made sure my changes work properly on Desktop.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by lipe-dev — APPROVED** [review]

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://79--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://79--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://79--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://79--logrock-pebbles.netlify.app&speed=1

**Comment by logrock-eng** [comment]
# Netlify Preview Deployed 

 Preview: https://79--logrock-pebbles.netlify.app 

 ## View on Browserstack 

 https://live.browserstack.com/dashboard#os=iOS&os_version=15.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https://79--logrock-pebbles.netlify.app&speed=1

**Comment by luizdanielmlima** [comment]
No need to increase coverage for now (it decreased a bit because the DateInput test was skipped - it was failing for some reason after the react-input-mask library was used. I've spent 3h trying to mock it in many ways but couldnt make it work.

**Pull request merged**
